/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * API version: 1.6.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package harbor

type ProjectMember struct {

	// The role id 1 for projectAdmin, 2 for developer, 3 for guest
	RoleId int32 `json:"role_id,omitempty"`

	MemberUser *UserEntity `json:"member_user,omitempty"`

	MemberGroup *UserGroup `json:"member_group,omitempty"`
}
