/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * API version: 1.6.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package harbor

type RepFilter struct {

	// The replication policy filter kind. The valid values are project, repository and tag.
	Kind string `json:"kind,omitempty"`

	// The value of replication policy filter. When creating repository and tag filter, filling it with the pattern as string. When creating label filter, filling it with label ID as integer.
	Value string `json:"value,omitempty"`

	// Depraceted, use value instead. The replication policy filter pattern.
	Pattern string `json:"pattern,omitempty"`

	// This map object is the replication policy filter metadata.
	Metadata *interface{} `json:"metadata,omitempty"`
}
