/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * API version: 1.6.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package harbor

type ReplicationResponse struct {

	// UUID of the replication
	Uuid string `json:"uuid,omitempty"`
}
