/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * API version: 1.6.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package harbor

type Replication struct {

	// The ID of replication policy
	PolicyId int32 `json:"policy_id,omitempty"`
}
