/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * API version: 1.6.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package harbor

type Resource struct {

	// The replication policy list.
	ReplicationPolicies []RepPolicy `json:"replication_policies,omitempty"`
}
