/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * API version: 1.6.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package harbor

type UpdateJobs struct {

	// The ID of replication policy
	PolicyId int32 `json:"policy_id,omitempty"`

	// The status of jobs. The only valid value is stop for now.
	Status string `json:"status,omitempty"`
}
